services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-local
    ports:
      - "8083:8083"
    volumes:
      - ./src/test/resources/wiremock/mappings:/home/wiremock/mappings:ro
    command: --global-response-templating --verbose --port 8083
