services:

  pcs-api-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pcs-api-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 1s
      retries: 5

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    ports:
      - "${SERVICE_AUTH_PORT}:${SERVICE_AUTH_PORT}"
    environment:
      SERVER_PORT: ${SERVICE_AUTH_PORT}
      AUTH_PROVIDER_SERVICE_SERVER_JWT_KEY: ${AUTH_PROVIDER_SERVICE_SERVER_JWT_KEY}
      JAVA_TOOL_OPTIONS: -XX:UseSVE=0
      microserviceKeys_pcs_frontend: AAAAAAAAAAAAAAAA

volumes:
  pcs-api-db-data:
