package uk.gov.hmcts.reform.pcs.ccd.entity;

public enum ClaimGroundCategory implements HasRank {

    ASSURED_MANDATORY,
    ASSURED_DISCRETIONARY,
    SECURE_OR_FLEXIBLE_DISCRETIONARY,
    SECURE_OR_FLEXIBLE_MANDATORY,
    SECURE_OR_FLEXIBLE_MANDATORY_ALT,
    SECURE_OR_FLEXIBLE_DISCRETIONARY_ALT,
    INTRODUCTORY_DEMOTED_OTHER,
    INTRODUCTORY_DEMOTED_OTHER_NO_GROUNDS,
    WALES_STANDARD_OTHER_MANDATORY,
    WALES_STANDARD_OTHER_DISCRETIONARY,
    WALES_STANDARD_OTHER_ESTATE_MANAGEMENT,
    WALES_SECURE_MANDATORY,
    WALES_SECURE_DISCRETIONARY,
    WALES_SECURE_ESTATE_MANAGEMENT;

    @Override
    public int getRank() {
        return this.ordinal();
    }

}
