spring:
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  security:
    oauth2:
      client:
        registration:
          prd-admin:
            client-secret: ${IDAM_CLIENT_SECRET:dummy-secret-for-local}
          system-user:
            client-secret: ${IDAM_CLIENT_SECRET:dummy-secret-for-local}

idam:
  system-user:
    username: ${PCS_IDAM_SYSTEM_USERNAME:pcs-system-user@localhost}
    password: ${PCS_IDAM_SYSTEM_PASSWORD:password}
  prd-admin:
    username: ${PCS_PRD_ADMIN_USERNAME:prd-admin-user@localhost}
    password: ${PCS_PRD_ADMIN_PASSWORD:password}
