export const cyaIgnoreQuestions = [
  'Day',
  'Month',
  'Year',
  'Hour',
  'Minute',
  'Second',
  'Uploaded files',
  'Uploaded file',
  'Defendant’s first name',
  'Defendant’s last name',
  'I believe that the facts stated in this claim form are true.',
  'Enter a UK postcode',
  'Is the defendant’s correspondence address the same as the address of the property you’re claiming possession of?',
  'Do you know the defendant’s name?',
  'Selected options',
  'How much is the rent?',
  'The claimant believes that the facts stated in this claim form are true. I am authorised by the claimant to sign this statement.',
  'Do you know the underlessee or mortgagee’s correspondence address?',
  'Do you know the underlessee or mortgagee’s name?',
  'Do you want to resume your claim using your saved answers?'
];
