// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "All defendant details questions combined into one screen " (8748:187988) and other states

export const additionalDefendantDetails = {
  mainHeader: `Additional defendant details`,
  addDefendantLabel: `Add defendant`,
  addNewLabel: `Add new`,
  additionalDefendantDetails2Label: `Additional defendant details 2`,
  additionalDefendantDetailsLabel: `Additional defendant  details`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  brianLabel: `Brian`,
  buildingAndStreetLabel: `Building and Street`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  defendantsCorrespondenceAddressLabel: `Defendant's correspondence address`,
  defendantsFirstNameLabel: `Defendant’s first name`,
  defendantsLastNameLabel: `Defendant’s last name`,
  defendantsNameLabel: `Defendant’s name`,
  doYouKnowTheDefendantsLabel: `Do you know the defendant’s name?`,
  doYouKnowTheDefendantsLabel2: `Do you know the defendant’s correspondence address?`,
  donavonLabel: `Donavon`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterAddressManuallyLabel: `Enter address manually`,
  findAddressLabel: `Find address`,
  isTheDefendantsCorrespondenceAddressLabel: `Is the defendant's correspondence address the same as the address of the property you're claiming possession of?`,
  jamesLabel: `James`,
  key5StoneyStreetLabel: `5 Stoney Street`,
  lu29jbLabel: `LU2 9JB`,
  lutonLabel: `Luton`,
  makeAClaimCaption: `Make a claim`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  selectAnAddressLabel: `Select an address`,
  springfordLabel: `Springford`,
  townOrCityLabel: `Town or City`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  yesOption: `Yes`
};
