// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExU - Case file view (TBC) to view saved application" (1:39436) and other states

export const caseFileView = {
  mainHeader: `Case File View`,
  billyWrightBrianSpringfordLabel: `Billy Wright
Brian Springford`,
  caseDetailsLabel: `Case details`,
  caseDocumentsLabel: `Case documents`,
  caseNumber12345671234Label: `Case Number 1234567/1234`,
  caseNumber123456789101Label: `Case number: 1234-5678-9101`,
  claimFormLabel: `Claim form`,
  claimantsLabel: `Claimants:`,
  defendantsLabel: `Defendants:`,
  documents4Label: `Documents (4)`,
  draftHousingPossessionApplicationpdfLabel: `Draft Housing possession application.pdf`,
  folder2Label: `<folder 2>`,
  folder3Label: `<folder 3>`,
  goLabel: `Go`,
  groundsForPossessionLabel: `Grounds for possession`,
  hearingsLabel: `Hearings`,
  housingPossessionLabel: `Housing Possession`,
  key15GardenDriveLutonBedfordshireLabel: `15 Garden Drive, Luton, Bedfordshire, LU1 1AB`,
  key1Label: `1`,
  key2Label: `2`,
  key3Label: `3`,
  linkedCasesLink: `Linked Cases`,
  makeAGeneralApplicationLabel: `Make a general application`,
  nextStepLabel: `Next step`,
  notesLabel: `Notes`,
  partiesLabel: `Parties`,
  paymentHistoryLabel: `Payment History`,
  persistentDelayInPayingRentLabel: `Persistent delay in paying rent (ground 11)`,
  queriesTab: `Queries`,
  rentArrearsGround10Label: `Rent arrears (ground 10)`,
  rolesAndAccessLabel: `Roles and Access`,
  searchByDocumentNameLabel: `Search by document name`,
  selectActionLabel: `Select action`,
  selectAnOptionLabel: `--Select an option--`,
  seriousRentArrearsGround8Label: `Serious rent arrears (ground 8)`,
  serviceRequestLabel: `Service Request`,
  settleOrDiscontinueClaimLabel: `Settle or discontinue claim`,
  submitAndPayLabel: `Submit and pay`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  treetopsHousingLabel: `Treetops Housing`,
  uploadDocumentsLabel: `Upload documents`
};
