// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "Case list - search" (1:17763) and other states

export const caseList = {
  mainHeader: `Case list`,
  applyLabel: `Apply`,
  caseNumberLabel: `Case number`,
  caseTypeLabel: `Case Type`,
  civilLabel: `Civil`,
  claimNumberLabel: `Claim number`,
  claimantNamesLabel: `Claimant names`,
  dateClaimIssuedLabel: `Date claim issued`,
  dateIssuedLabel: `Date issued`,
  dayLabel: `Day`,
  defendantNamesLabel: `Defendant names`,
  filtersLabel: `Filters`,
  forExample1642021HintText: `For example, 16 4 2021`,
  hideFilterLabel: `Hide filter`,
  housingPossessionLabel: `Housing Possession`,
  jurisdictionLabel: `Jurisdiction`,
  labelLabel: `Label`,
  legendLabel: `Legend`,
  monthLabel: `Month`,
  pleaseEnterDateLabel: `Please enter date`,
  postcodeLabel: `Postcode`,
  propertyPostcodeLabel: `Property postcode`,
  resetLabel: `Reset`,
  selectAValueLabel: `--Select a value--`,
  showing1To3OfLabel: `Showing 1 to 3 of 3 results`,
  showingXxxxToYyyyOfLabel: `Showing XXXX to YYYY of ZZZZ results`,
  stateLabel: `State`,
  statusLabel: `Status`,
  wrightLabel: `Wright`,
  yearLabel: `Year`,
  yourCasesLabel: `Your cases`
};
