// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExUI - Check your answers (including content) - Rent arrears " (2453:122433) and other states

export const checkYourAnswers = {
  mainHeader: `Check your answers`,
  aJudgeHasMadeAnLabel: `A judge has made an order`,
  aRegisteredProviderOfSocialLabel: `A registered provider of social housing`,
  alternativesToPossessionLabel: `Alternatives to Possession`,
  applicationsLabel: `Applications`,
  areYouClaimingPossessionBecauseLabel: `Are you claiming possession because of rent arrears?`,
  areYouPlanningToSubmitLabel: `Are you planning to submit a general application at the same time as your claim?`,
  assuredTenancyLabel: `Assured tenancy`,
  billyLabel: `Billy`,
  byFirstClassPostOrLabel: `By first class post or other service which provides for delivery on the next business day`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  changeLink: `Change`,
  claimDetailsLabel: `Claim details`,
  claimantAndDefendantCircumstancesLabel: `Claimant and Defendant circumstances`,
  claimingCostsLabel: `Claiming costs`,
  contactPreferencesLabel: `Contact Preferences`,
  dateTheDocumentWasPostedLabel: `Date the document was posted`,
  defendantDetailsLabel: `Defendant details`,
  defendantsFirstNameLabel: `Defendant’s first name`,
  defendantsLastNameLabel: `Defendant’s last name`,
  detailsOfStepsTakenLabel: `<details of steps taken>`,
  didYouCompleteAllOrLabel: `Did you complete all or part of this [thing name] in Welsh?`,
  discretionaryHousingPaymentLabel: `Discretionary Housing Payment`,
  doYouHaveAnyOtherLabel: `Do you have any other grounds for possession?`,
  doYouKnowTheDefendantsLabel: `Do you know the defendant’s name?`,
  doYouKnowTheDefendantsLabel2: `Do you know the defendant’s correspondence address`,
  doYouKnowTheDefendantsLabel3: `Do you know the defendant’s email address? (Optional)`,
  doYouWantDocumentsToLabel: `Do you want documents to be sent to this address?`,
  doYouWantTheCourtLabel: `Do you want the court to make a judgment for the outstanding arrears?`,
  doYouWantToAskLabel: `Do you want to ask for your costs back?`,
  doYouWantToProvideLabel: `Do you want to provide a contact phone number?`,
  doYouWantToProvideLabel2: `Do you want to provide a contact phone number? (Optional)`,
  doYouWantToUploadLabel: `Do you want to upload a copy of the tenancy or licence agreement? (Optional)`,
  doYouWantToUploadLabel2: `Do you want to upload a copy of the notice you served or the certificate of service? (Optional)`,
  doYouWantToUploadLabel3: `Do you want to upload any additional documents?`,
  doYouWantToUseLabel: `Do you want to use this email address for notifications?`,
  englishAndWelshLabel: `English and Welsh`,
  enterTheDateOfTheLabel: `Enter the date of the order setting aside the judgment`,
  explainWhatStepsYouveTakenLabel: `Explain what steps you’ve taken to reach a settlement (optional)`,
  forThePeriodShownOnLabel: `For the period shown on the rent statement, have any rent payments been paid by someone other than the defendants?`,
  giveDetailsAboutTheDefendantsLabel: `Give details about the defendants’ circumstances`,
  groundsAndPreactionRequirementsLabel: `Grounds and Pre-action Requirements`,
  haveYouAttemptedMediationWithLabel: `Have you attempted mediation with the defendants?`,
  haveYouFollowedThePreactionLabel: `Have you followed the pre-action protocol?`,
  haveYouServedNoticeToLabel: `Have you served notice to the defendants?`,
  haveYouTriedToReachLabel: `Have you  tried to reach a settlement with the defendants?`,
  homelessPreventionFundLabel: `Homeless prevention fund`,
  housingBenefitLabel: `Housing Benefit`,
  howDidYouServeTheLabel: `How did you serve the notice?`,
  howFrequentlyShouldRentBeLabel: `How frequently should rent be paid?`,
  howMuchAreTheTotalLabel: `How much are the total rent arrears as shown on the rent statement?`,
  howMuchIsTheRentLabel: `How much is the rent?`,
  inTheAlternativeToPossessionLabel: `In the alternative to possession, would you like to claim demotion of tenancy or suspension of right to buy?`,
  isTheAmountPerDayLabel: `Is the amount per day that unpaid rent should be charged at correct?`,
  isTheDefendantsCorrespondenceAddressLabel: `Is the defendant's correspondence address the same as the address of the property you're claiming possession of?`,
  isThereAnUnderleseeOrLabel: `Is there an underlesee or mortgagee entitled to claim relief against forfeiture?`,
  isThereAnyInformationYoudLabel: `Is there any information you’d like to provide about Treetops Housing’s circumstances?`,
  isThereAnyInformationYoudLabel2: `Is there any information you’d like to provide about the defendants’ circumstances?`,
  isThereAnyOtherInformationLabel: `Is there any other information you’d like to provide about your reasons for possession?`,
  isThisAClaimAgainstLabel: `Is this a claim against trespassers?`,
  isThisTheCorrectClaimantLabel: `Is this the correct claimant name?`,
  johnsonVEvansLabel: `Johnson v Evans`,
  key0422015Label: `04/2/2015`,
  key1234567891011213Label: `#1234-5678-9101-1213`,
  key125Label: `£125`,
  key15GardenDriveLutonBedfordshireLabel: `15 Garden Drive
Luton
Bedfordshire
LU1 1AB`,
  key1625Label: `1/6/25`,
  key1645472831177850Label: `#1645-4728-3117-7850`,
  key21042023Label: `21-04-2023`,
  key3050Label: `£3050`,
  languageUsedLabel: `Language used`,
  mediationAndSettlementLabel: `Mediation and Settlement`,
  noOption: `No`,
  notice15gardendrivepdfLabel: `Notice_15_Garden-Drive.pdf`,
  noticeOfPossessionLabel: `Notice of Possession`,
  orderFollowingAnApplicationToLabel: `Order following an application to set aside`,
  otherPaymentSourceLabel: `<Other payment source>`,
  paymentHistoryLabel: `Payment History`,
  previousLabel: `Previous`,
  reasonsForPossessionLabel: `Reasons for Possession`,
  rentAndArrearsInformationForm: `Rent and Arrears Information`,
  rentstatement15gardendrivepdfLabel: `Rent_statement_15_Garden-Drive.pdf`,
  saveClaimLabel: `Save claim`,
  secureTenancyLabel: `Secure tenancy`,
  seriousRentArrearsGround8Label: `Serious rent arrears (ground 8)
Rent arrears (ground 10)
Persistent delay in paying rent (ground 11)`,
  submitAndPayLabel: `Submit and pay`,
  submitClaimLabel: `Submit claim`,
  submitLabel: `Submit`,
  supportingDocumentsLabel: `Supporting Documents`,
  tenancyInformationDetailsForm: `Tenancy information details`,
  tenancyagreement15gardendrivepdfLabel: `Tenancy_agreement_15_Garden-Drive.pdf`,
  tenantsLabel: `Tenants`,
  theDefendantLivesWithTheirLabel: `The defendant lives with their 3 children at the property. They are receiving Universal Credit and housing benefit and are in part-time employment. No deductions are being made from their benefits to pay off the arrears.`,
  underlesseeOrMortgageeLabel: `Underlessee or mortgagee`,
  universalCreditLabel: `Universal Credit`,
  uploadTheRentStatementLabel: `Upload the rent statement`,
  weeklyLabel: `Weekly`,
  whatAreYourGroundsForLabel: `What are your grounds for possession?`,
  whatDateDidTheTenancyLabel: `What date did the tenancy or licence begin? (Optional)`,
  whatIsTheAddressOfLabel: `What is the address of the property you’re claiming possession of?`,
  whatTypeOfTenancyOrLabel: `What type of tenancy or licence is in place?`,
  whereHaveThePaymentsComeLabel: `Where have the payments come from?`,
  whichLanguageDidYouUseLabel: `Which language did you use to complete this service?`,
  whichTypeOfOrderHasLabel: `Which type of order has been made?`,
  whoAreYouMakingALabel: `Who are you making a possession claim against?`,
  whoIsTheClaimantInLabel: `Who is the claimant in this case?`,
  whyIsThisJudgmentBeingLabel: `Why is this judgment being set aside?`,
  wrightLabel: `Wright`,
  yesOption: `Yes`
};
