// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExU - 02 Case details" (1:38583) and other states

export const claim = {
  mainHeader: `Claim`,
  accumulatedArrearsLabel: `Accumulated arrears`,
  action1Label: `Action 1`,
  action2Label: `Action 2`,
  action3Label: `Action 3`,
  addressLabel: `Address`,
  addressOfPropertyToBeLabel: `Address of property to be repossessed`,
  amountDueLabel: `Amount due`,
  amountPaidLabel: `Amount paid`,
  assuredLabel: `Assured`,
  billyLabel: `Billy`,
  buildingAndStreetLabel: `Building and Street`,
  caseDetailsLabel: `Case details`,
  caseFileViewLabel: `Case File View`,
  caseNumber123456789101Label: `Case number: 1234-5678-9101`,
  claimantDetailsLabel: `Claimant details`,
  claimantNameLabel: `Claimant name`,
  claimantsDetailsLabel: `Claimant's details`,
  countryLabel: `Country`,
  datePaymentDueLabel: `Date payment due`,
  defendant1CorrespondenceAddressLabel: `Defendant 1 correspondence address`,
  defendant1Label: `Defendant 1`,
  defendant2CorrespondenceAddressLabel: `Defendant 2 correspondence address`,
  defendant2Label: `Defendant 2`,
  defendantDetailsLabel: `Defendant details`,
  firstNameLabel: `First name`,
  firstPaymentLabel: `First payment`,
  goLabel: `Go`,
  groundsForPossessionLabel: `Grounds for possession`,
  hearingsLabel: `Hearings`,
  key0Label: `£0`,
  key125Label: `£125`,
  key15GardenDriveLabel: `15 Garden Drive`,
  key15GardenDriveLutonBedfordshireLabel: `15 Garden Drive, Luton, Bedfordshire, LU1 1AB`,
  key1HighStreetLabel: `1 High Street`,
  key31012025Label: `31.01/2025`,
  key51215Label: `5/12/15`,
  lastNameLabel: `Last name`,
  linkedCasesLink: `Linked Cases`,
  lu11abLabel: `LU1 1AB`,
  lu11bcLabel: `LU1 1BC`,
  lutonLabel: `Luton`,
  makeAGeneralApplicationLabel: `Make a general application`,
  nextStepLabel: `Next step`,
  notesLabel: `Notes`,
  organisationAddressLabel: `Organisation Address`,
  partiesLabel: `Parties`,
  paymentDetailsLabel: `Payment details`,
  paymentHistoryLabel: `Payment History`,
  paymentHistoryLabel2: `Payment history`,
  postcodezipcodeLabel: `Postcode/Zipcode`,
  preActionProtocolLabel: `Pre action protocol`,
  queriesTab: `Queries`,
  rolesAndAccessLabel: `Roles and Access`,
  secondPaymentLabel: `Second payment`,
  selectAnOptionLabel: `--Select an option--`,
  seriousRentArrearsGround8Label: `Serious rent arrears (ground 8)
Rent arrears (ground 10)
Persistent delay in paying rent (ground 11)`,
  serviceRequestLabel: `Service Request`,
  settleOrDiscontinueClaimLabel: `Settle or discontinue claim`,
  submitAndPayLabel: `Submit and pay`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  tenancyOrLicenceAgreementLabel: `Tenancy or licence agreement`,
  tenancyOrLicenceDetailsLabel: `Tenancy or licence details`,
  tenancyOrLicenceStartDateLabel: `Tenancy or licence start date`,
  textLabel: `Text`,
  textParagraph2Label: `Text paragraph 2`,
  townOrCityLabel: `Town or City`,
  treetopsHousingLabel: `Treetops Housing`,
  unitedKingdomLabel: `United Kingdom`,
  uploadDocumentsLabel: `Upload documents`,
  whatHappensNextLabel: `What happens next`,
  wrightLabel: `Wright`,
  yourPossessionClaimHasBeenLabel: `Your possession claim has been made. The claim will be sent to the defendants to give them the opportunity to respond. A hearing will then be scheduled..`
};
