// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "Q1 - No variant" (8748:141975) and other states

export const defendantsName = {
  mainHeader: `Defendant’s name`,
  addDocumentLabel: `Add document`,
  addNewLabel: `Add new`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  brianLabel: `Brian`,
  buildingAndStreetLabel: `Building and Street`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  defendantsCorrespondenceAddressLabel: `Defendant's correspondence address`,
  defendantsFirstNameLabel: `Defendant’s first name`,
  defendantsLastNameLabel: `Defendant’s last name`,
  doYouKnowTheDefendantsLabel: `Do you know the defendant’s name?`,
  doYouKnowTheDefendantsLabel2: `Do you know the defendant’s correspondence address?`,
  documentLabel: `Document`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterAddressManuallyLabel: `Enter address manually`,
  findAddressLabel: `Find address`,
  isTheDefendantsCorrespondenceAddressLabel: `Is the defendant's correspondence address the same as the address of the property you're claiming possession of?`,
  key5StoneyStreetLabel: `5 Stoney Street`,
  lu29jbLabel: `LU2 9JB`,
  lutonLabel: `Luton`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  removeLabel: `Remove`,
  selectAnAddressLabel: `Select an address`,
  springfordLabel: `Springford`,
  townOrCityLabel: `Town or City`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  yesOption: `Yes`
};
