// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "All defendant details questions combined into one screen " (8748:141226) and other states

export const defendantDetails = {
  mainHeader: `Defendant details`,
  addADefendantToTheLabel: `Add a defendant to the case`,
  addAdditionalDefendant2Label: `Add additional defendant 2`,
  addAdditionalDefendantLabel: `Add additional defendant`,
  addAnAdditionalDefendantToLabel: `Add an additional defendant to the case`,
  addDefendant2Label: `Add defendant 2`,
  addDefendantLabel: `Add defendant`,
  addNewLabel: `Add new`,
  additionalDefendantsLabel: `Additional defendants`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  billyLabel: `Billy`,
  brianLabel: `Brian`,
  buildingAndStreetLabel: `Building and Street`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  defendantDetails2Label: `Defendant details 2`,
  defendantsCorrespondenceAddressLabel: `Defendant's correspondence address`,
  defendantsFirstNameLabel: `Defendant’s first name`,
  defendantsLastNameLabel: `Defendant’s last name`,
  defendantsNameLabel: `Defendant’s name`,
  doWeNeedAHeadingLabel: `Do we need a heading????
Potential copy to instruct the user to add the details of defendants???`,
  doYouKnowTheDefendantsLabel: `Do you know the defendant’s name?`,
  doYouKnowTheDefendantsLabel2: `Do you know the defendant’s correspondence address?`,
  doYouNeedToAddLabel: `Do you need to add another defendant?`,
  donavonLabel: `Donavon`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterAddressManuallyLabel: `Enter address manually`,
  findAddressLabel: `Find address`,
  hintHintText: `Hint`,
  iCantEnterAUkLabel: `I can’t enter a UK postcode`,
  ifTheirCorrespondenceAddressIsHintText: `If their correspondence address is outside of the UK, you’ll need to make a general application for permission to serve a claim outside the jurisdiction after you’ve submitted and paid for the claim`,
  isTheDefendantsCorrespondenceAddressLabel: `Is the defendant's correspondence address the same as the address of the property you're claiming possession of?`,
  jamesLabel: `James`,
  key5StoneyStreetLabel: `5 Stoney Street`,
  lu29jbLabel: `LU2 9JB`,
  lutonLabel: `Luton`,
  makeAClaimCaption: `Make a claim`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  selectAnAddressLabel: `Select an address`,
  simonLabel: `Simon`,
  smithLabel: `Smith`,
  springfordLabel: `Springford`,
  townOrCityLabel: `Town or City`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  wrightLabel: `Wright`,
  yesOption: `Yes`
};
