// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExUI - Dashboard" (1:26033) and other states

export const key15GardenDriveLutonBedfordshire = {
  mainHeader: `15 Garden Drive, Luton, Bedfordshire, LU1 1AB
Case number: 1234-5678-9101`,
  amountLabel: `Amount`,
  amountToPay40400Label: `Amount to pay
£404.00`,
  applicationLabel: `Application`,
  c2Label: `C2`,
  cancelLabel: `Cancel`,
  caseDetailsLabel: `Case details`,
  caseDocumentsLabel: `Case Documents`,
  caseFileViewLabel: `Case File View`,
  caseNumber123456789101Label: `Case number: 1234-5678-9101`,
  commentsLabel: `Comments`,
  confidentialInformationForm: `Confidential Information`,
  continueLabel: `Continue`,
  correspondenceLabel: `Correspondence`,
  courtBundleLabel: `Court Bundle`,
  creationDateLabel: `Creation date`,
  creationStatusLabel: `Creation status`,
  ctaLabel: `CTA`,
  documentsInASpecifiedColourLabel: `Documents in a specified colour`,
  documentsLabel: `Documents`,
  documentsSentToPartiesLabel: `Documents Sent to Parties`,
  enterAReferenceForYourLabel: `Enter a reference for your PBA account statements`,
  expertReportsLabel: `Expert Reports`,
  flagStatusLabel: `Flag status`,
  gardenDriveClaimFeeLabel: `Garden Drive claim fee`,
  goLabel: `Go`,
  hearingsLabel: `Hearings`,
  historyLabel: `History`,
  johnSmithLabel: `John Smith`,
  judicialMessagesLabel: `Judicial Messages`,
  key11525Label: `11/5/25`,
  key202417163031067Label: `2024-17163031067`,
  key404Label: `£404`,
  key6525Label: `6/5/25`,
  languageInterpreterLabel: `Language interpreter`,
  lastModifiedLabel: `Last modified`,
  legalBasisLabel: `Legal Basis`,
  linkedCasesLink: `Linked Cases`,
  makeAGeneralApplicationLabel: `Make a general application`,
  nextStepLabel: `Next step`,
  nextStepsLabel: `Next steps`,
  noOption: `No`,
  notPaidLabel: `Not paid`,
  notesLabel: `Notes`,
  ordersLabel: `Orders`,
  partiesLabel: `Parties`,
  partyLabel: `Party`,
  partyLevelFlagsLabel: `Party level flags`,
  payFeeByCreditOrLabel: `Pay fee by credit or debit card`,
  payFeeUsingPaymentByLabel: `Pay fee using Payment by Account (PBA)`,
  payNowLabel: `Pay now`,
  paymentHistoryLabel: `Payment History`,
  pba0081571Label: `PBA0081571`,
  peopleInTheCaseLabel: `People in the Case`,
  personA1Label: `Person A 1`,
  personB1Label: `Person B 1`,
  placementLabel: `Placement`,
  previousLabel: `Previous`,
  queriesTab: `Queries`,
  reasonableAdjustmentLabel: `Reasonable adjustment`,
  requestReferenceLabel: `Request reference`,
  requestSupportLabel: `Request support`,
  requestedLabel: `REquested`,
  resumeClaimLabel: `Resume claim`,
  reviewLabel: `Review`,
  rolesAndAccessLabel: `Roles and Access`,
  selectActionLabel: `Select action`,
  selectAnOptionLabel: `--Select an option--`,
  selectOptionLabel: `Select option`,
  selectPbaLabel: `Select PBA`,
  serviceRequestLabel: `Service Request`,
  settleOrDiscontinueClaimLabel: `Settle or discontinue claim`,
  spanishInterpreterNeededLabel: `Spanish interpreter needed`,
  statusLabel: `Status`,
  summaryLabel: `Summary`,
  supportNeededLabel: `Support needed`,
  supportRequestedLabel: `Support requested`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  thisShouldBeYourOwnHintText: `This should be your own unique reference to identify the case.  It will appear on your statement`,
  treetopsHousingLabel: `Treetops Housing`,
  unnamedLabel: `?`,
  uploadDocumentsLabel: `Upload documents`,
  viewApplicationLabel: `View Application`,
  youveAlreadyAnsweredSomeQuestionsLabel: `You’ve already answered some questions about this claim.`
};
