// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "Rent or Breach - A" (1767:110659) and other states

export const mainHeading = {
  mainHeader: `Main heading`,
  addDocumentLabel: `Add document`,
  addNewLabel: `Add new`,
  areYouClaimingPossessionBecauseLabel: `Are you claiming possession because of rent arrears or breach of the tenancy (ground 1)?`,
  breachOfTheTenancyLabel: `Breach of the tenancy`,
  cancelLabel: `Cancel`,
  captionUsuallyTheNextStepCaption: `Caption (usually the ‘Next step’ menu text)`,
  continueLabel: `Continue`,
  dayLabel: `Day`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  findAddressLabel: `Find address`,
  forExample1642021HintText: `For example, 16 4 2021, 11 15 00`,
  hintHintText: `Hint`,
  hourLabel: `Hour`,
  iCantEnterAUkLabel: `I can’t enter a UK postcode`,
  key50AddressesFoundLabel: `50 addresses found`,
  labelLabel: `Label`,
  legendLabel: `Legend`,
  minuteLabel: `Minute`,
  monthLabel: `Month`,
  pleaseEnterAddressDetailsLabel: `Please enter address details`,
  pleaseEnterDateAndTimeLabel: `Please enter date and time`,
  previousLabel: `Previous`,
  rentArrearsLabel: `Rent arrears`,
  secondLabel: `Second`,
  selectAllThatApplyHintText: `Select all that apply`,
  selectAnAddressLabel: `Select an address`,
  subheadBodyTextWithLinkLabel: `Subhead
Body text with link`,
  subheading1UsuallyCaseNumberLabel: `Subheading 1 (usually case number)`,
  subheading2Label: `Subheading 2`,
  subheading3Label: `Subheading 3`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  w1w7rtLabel: `W1W 7RT`,
  whatDoesYourClaimInvolveLabel: `What does your claim involve?`,
  yearLabel: `Year`
};
