// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExU - 02 Claim details" (1:38444) and other states

export const possessionDetails = {
  mainHeader: `Possession details`,
  accumulatedArrearsLabel: `Accumulated arrears`,
  addressLabel: `Address`,
  amountDueLabel: `Amount due`,
  amountPaidLabel: `Amount paid`,
  billyLabel: `Billy`,
  buildingAndStreetLabel: `Building and Street`,
  caseDetailsLabel: `Case details`,
  caseFileViewLabel: `Case File View`,
  caseNumber123456789101Label: `Case number: 1234-5678-9101`,
  claimMadeLabel: `Claim made`,
  claimantDetailsLabel: `Claimant details`,
  claimantNameLabel: `Claimant name`,
  claimantsDetailsLabel: `Claimant's details`,
  countryLabel: `Country`,
  dateClaimSubmittedLabel: `Date claim Submitted`,
  datePaymentDueLabel: `Date payment due`,
  defendantDetailsLabel: `Defendant details`,
  deleteThisCaseLabel: `Delete this case`,
  firstNameLabel: `First name`,
  firstPaymentLabel: `First payment`,
  goLabel: `Go`,
  gourndsForPossessionLabel: `Gournds for possession`,
  hearingsLabel: `Hearings`,
  johnsonVEvansLabel: `Johnson v Evans`,
  key0Label: `£0`,
  key15GardenDriveLabel: `15 Garden Drive`,
  key15GardenDriveLutonBedfordshireLabel: `15 Garden Drive, Luton, Bedfordshire, LU1 1AB`,
  key1645472831177850Label: `#1645-4728-3117-7850`,
  key1HighStreetLabel: `1 High Street`,
  key250Label: `£250`,
  key31012025Label: `31.01/2025`,
  key6May202510AmLabel: `6 May 2025, 10 AM`,
  key6thMay202510AmLabel: `6th May 2025, 10 AM`,
  lastNameLabel: `Last name`,
  linkedCasesLink: `Linked Cases`,
  lu11abLabel: `LU1 1AB`,
  lu11bcLabel: `LU1 1BC`,
  lu11cdLabel: `LU1 1CD`,
  lutonLabel: `Luton`,
  makeAGeneralApplicationLabel: `Make a general application`,
  nextStepLabel: `Next step`,
  notesLabel: `Notes`,
  organisationAddressLabel: `Organisation Address`,
  partiesLabel: `Parties`,
  paymentHistoryLabel: `Payment History`,
  paymentHistoryLabel2: `Payment history`,
  pba1356448Label: `PBA1356448`,
  pbaNumberLabel: `PBA Number`,
  postcodezipcodeLabel: `Postcode/Zipcode`,
  propertyDetailsLabel: `Property details`,
  queriesTab: `Queries`,
  reviewTheClaimBeforeYouLabel: `Review the claim before you sign, submit and pay.`,
  rolesAndAccessLabel: `Roles and Access`,
  selectActionLabel: `Select action`,
  selectAnOptionLabel: `--Select an option--`,
  seriousRentArrearsGround8Label: `Serious rent arrears (ground 8)
Rent arrears (ground 10)
Persistent delay in paying rent (ground 11)`,
  serviceRequestLabel: `Service Request`,
  settleOrDiscontinueClaimLabel: `Settle or discontinue claim`,
  submitAndPayLabel: `Submit and pay`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  theClaimWillBeSentLabel: `The claim will be sent to the defendants and they will be given the opportunity to submit a response. A hearing date will be scheduled where a judge will listen to both sides and make a decision.`,
  townOrCityLabel: `Town or City`,
  treetopsHousingLabel: `Treetops Housing`,
  unitedKingdomLabel: `United Kingdom`,
  uploadDocumentsLabel: `Upload documents`,
  whatHappensNextLabel: `What happens next`,
  wrightLabel: `Wright`,
  yourPossessionClaimHasBeenLabel: `Your possession claim has been made. The claim will be sent to the defendants to give them the opportunity to respond. A hearing will then be scheduled.`
};
