// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExUI - Text" (7652:122914) and other states

export const requestSupport = {
  mainHeader: `Request support`,
  addSupportToLabel: `Add support to`,
  audioTranslationOfDocumentsLabel: `Audio translation of documents`,
  billyWrightLabel: `Billy Wright`,
  brailleDocumentsLabel: `Braille documents`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  changeLink: `Change`,
  continueLabel: `Continue`,
  defendants1Label: `<Defendants 1>`,
  defendants2Label: `<Defendants 2>`,
  detailsOfTheRequestLabel: `<Details of the request>`,
  documentsInASpecifiedColourLabel: `Documents in a specified colour`,
  documentsInEasyToReadLabel: `Documents in easy to read format`,
  documentsInLargePrintLabel: `Documents in large print`,
  documentsReadOutToMeLabel: `Documents read out to me`,
  explainWhyYouAreCreatingHintText: `Explain why you are creating this support request. DO not include any sensitive information such as personal details.`,
  iNeedAdjustmentsToGetLabel: `I need adjustments to get to, into and around the building`,
  iNeedDocumentsInAnLabel: `I need documents in an alternative format`,
  iNeedHelpCommunicatingAndLabel: `I need help communicating and understanding`,
  iNeedHelpWithFormsLabel: `I need help with forms`,
  iNeedSomethingToFeelLabel: `I need something to feel comfortable during my hearing`,
  iNeedToBringSupportLabel: `I need to bring support with me to a hearing`,
  iNeedToRequestALabel: `I need to request a certain type of hearing`,
  informationEmailedToMeLabel: `Information emailed to me`,
  languageInterpreterLabel: `Language interpreter`,
  otherLabel: `Other`,
  previousLabel: `Previous`,
  reasonableAdjustmentLabel: `Reasonable adjustment`,
  requestedLabel: `Requested`,
  selectSupportTypeLabel: `Select support type`,
  statusLabel: `Status`,
  supportTypeLabel: `Support type`,
  tellUsMoreAboutTheLabel: `Tell us more about the request (optional)`,
  whoIsTheSupportForLabel: `Who is the support for?`
};
