// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "ExUI - Dashboard" (1:26126) and other states

export const serviceRequest = {
  mainHeader: `Service request`,
  addRemissionLabel: `Add remission`,
  amountLabel: `Amount`,
  backLink: `Back`,
  caseDetailsLabel: `Case details`,
  caseFileViewLabel: `Case File View`,
  ccdEventLabel: `CCD event`,
  dateCreatedLabel: `Date created`,
  feeLabel: `Fee`,
  goLabel: `Go`,
  hearingsLabel: `Hearings`,
  helpWithFeesOrRemissionLabel: `Help with fees or remission code`,
  issueRefundLabel: `Issue refund`,
  key09April2025Label: `09 April 2025`,
  key11Apr2025Label: `11 Apr 2025`,
  key15GardenDriveLutonBedfordshireLabel: `15 Garden Drive, Luton, Bedfordshire, LU1 1AB
Case number: 1234-5678-9101`,
  key1X26300Label: `1 X £263.00`,
  key20251750000016388Label: `2025-1750000016388`,
  key26300Label: `£263.00`,
  linkedCasesLink: `Linked Cases`,
  nextStepLabel: `Next step`,
  noHelpWithFeesOrLabel: `No help with fees or remissions`,
  notPaidLabel: `Not paid`,
  notesLabel: `Notes`,
  partiesLabel: `Parties`,
  partyLabel: `Party`,
  paymentHistoryLabel: `Payment History`,
  paymentLabel: `payment`,
  paymentsLabel: `Payments`,
  qaTest488CaLabel: `QA test 488 - CA`,
  queriesTab: `Queries`,
  referenceLabel: `Reference`,
  reviewLabel: `Review`,
  rolesAndAccessLabel: `Roles and Access`,
  section8OrdersSection101Label: `Section 8 orders (section 10(1) or (2))`,
  selectAnOptionLabel: `--Select an option--`,
  serviceRequestLabel: `Service Request`,
  serviceRequestReferenceLabel: `Service request reference`,
  statusLabel: `Status`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  textLabel: `Text`,
  totalFees26300Label: `Total fees: £263.00`,
  totalFeesLeftToPayLabel: `Total fees left to pay: £263.00`,
  totalFeesToPay26300Label: `Total fees to pay: £263.00`,
  totalLabel: `Total`,
  totalReductions000Label: `Total reductions: £0.00`
};
