// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "All defendant details questions combined into one screen " (1:29587) and other states

export const tenancyOrLicenceDetails = {
  mainHeader: `Tenancy or licence details`,
  addDocumentLabel: `Add document`,
  addNewLabel: `Add new`,
  assuredTenancyLabel: `Assured tenancy`,
  cancelLabel: `Cancel`,
  cancelUploadLabel: `Cancel upload`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  chooseFileLabel: `Choose file`,
  continueLabel: `Continue`,
  dayLabel: `Day`,
  demotedTenancyLabel: `Demoted tenancy`,
  doYouWantToUploadLabel: `Do you want to upload a copy of the tenancy or licence agreement? (Optional)`,
  documentLabel: `Document`,
  flexibleTenancyLabel: `Flexible tenancy`,
  forExample1642021HintText: `For example, 16 4 2021`,
  giveDetailsOfTheTypeLabel: `Give details of the type of tenancy or licence agreement that’s in place`,
  iWantToSaveThisLabel: `I want to save this application and return to it later`,
  introductoryTenancyLabel: `Introductory tenancy`,
  key04Label: `04`,
  key2015Label: `2015`,
  key2Label: `2`,
  makeAClaimCaption: `Make a claim`,
  monthLabel: `Month`,
  noFileChosenLabel: `No file chosen`,
  otherLabel: `Other`,
  pleaseEnterDateLabel: `Please enter date`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  secureTenancyLabel: `Secure tenancy`,
  tenancyOrLicenceStartDateLabel: `Tenancy or licence start date`,
  tenancyOrLicenceTypeLabel: `Tenancy or licence type`,
  tenancyagreement15gardendrivepdfLabel: `Tenancy_agreement_15_Garden-Drive.pdf`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  uploadTenancyOrLicenceAgreementLabel: `Upload tenancy or licence agreement`,
  whatDateDidTheTenancyLabel: `What date did the tenancy or licence begin? (Optional)`,
  whatTypeOfTenancyOrLabel: `What type of tenancy or licence is in place?`,
  yearLabel: `Year`,
  youCanEitherUploadThisHintText: `You can either upload this now or closer to the hearing date. Any documents you upload now will be included in the pack of documents a judge will receive before the hearing (the bundle)`,
  youCanEitherUploadThisHintText2: `You can either upload this now or closer to the hearing date. Any documents you upload now will be included in the pack of documents a judge will receive before the hearing (the bundle).`
};
