// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "Refined - Underlessee name" (8748:199632) and other states

export const underlesseeOrMortgageeDetails = {
  mainHeader: `Underlessee or mortgagee details`,
  addAUnderlesseeOrMortgageeLabel: `Add a underlessee or mortgagee to the case`,
  addNewLabel: `Add new`,
  addUnderlesseeOrMortgagee1Label: `Add underlessee or mortgagee 1`,
  addUnderlesseeOrMortgagee2Label: `Add underlessee or mortgagee 2`,
  addUnderlesseeOrMortgageeLabel: `Add underlessee or mortgagee`,
  additionalUnderlesseeOrMortgageeLabel: `Additional underlessee or mortgagee?`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  bradDolanLabel: `Brad Dolan`,
  buildingAndStreetLabel: `Building and Street`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  doYouKnowTheUnderlesseeLabel: `Do you know the underlessee or mortgagee’s name?`,
  doYouKnowTheUnderlesseeLabel2: `Do you know the underlessee or mortgagee’s correspondence address?`,
  doYouNeedToAddLabel: `Do you need to add another underlessee or mortgagee?`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterTheirFirstAndLastHintText: `Enter their first and last name, or the company or organisation name`,
  findAddressLabel: `Find address`,
  iCantEnterAUkLabel: `I can’t enter a UK postcode`,
  key14LongStreetLabel: `14 Long Street`,
  key14LongStreetLutonLabel: `14 Long Street, Luton`,
  lu56tbLabel: `LU5 6TB`,
  lutonLabel: `Luton`,
  makeAClaimCaption: `Make a claim`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  selectAnAddressLabel: `Select an address`,
  townOrCityLabel: `Town or City`,
  underlesseeOrMortgageeCorrespondenceAddressLabel: `Underlessee or mortgagee correspondence address`,
  underlesseeOrMortgageeNameLabel: `Underlessee or mortgagee name`,
  whatIsTheirNameLabel: `What is their name?`,
  yesOption: `Yes`
};
