// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "Refined - Underlessee name" (4131:120700) and other states

export const underlesseeOrMortgagee2Details = {
  mainHeader: `Underlessee or mortgagee 2 details`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  bradDolanLabel: `Brad Dolan`,
  buildingAndStreetLabel: `Building and Street`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  doYouKnowTheUnderlesseeLabel: `Do you know the underlessee or mortgagee’s name?`,
  doYouKnowTheUnderlesseeLabel2: `Do you know the underlessee or mortgagee’s correspondence address?`,
  doYouKnowTheirNameLabel: `Do you know their name?`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterTheirFirstAndLastHintText: `Enter their first and last name, or the company or organisation name`,
  findAddressLabel: `Find address`,
  jamesDeanLabel: `James Dean`,
  key14ShortStreetLabel: `14 Short Street`,
  key14ShortStreetLutonLabel: `14 Short Street, Luton`,
  lu78tbLabel: `LU7 8TB`,
  lutonLabel: `Luton`,
  makeAClaimCaption: `Make a claim`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  previousLabel: `Previous`,
  selectAnAddressLabel: `Select an address`,
  townOrCityLabel: `Town or City`,
  underlesseeOrMortgageeCorrespondenceAddressLabel: `Underlessee or mortgagee correspondence address`,
  underlesseeOrMortgageeNameLabel: `Underlessee or mortgagee name`,
  whatIsTheirNameLabel: `What is their name?`,
  yesOption: `Yes`
};
