// Auto-generated from Figma file: MHSqNylYUQUmLbWCQeBHqq, based on page: "GfP - all (B) / RA grounds hidden" (8669:140425) and other states

export const whatAreYourAdditionalGrounds = {
  mainHeader: `What are your additional grounds for possession?`,
  adaptedAccommodationGround13Label: `Adapted accommodation (ground 13)`,
  antisocialBehaviourGround7aLabel: `Antisocial behaviour (ground 7A)`,
  antisocialBehaviourLabel: `Antisocial behaviour`,
  breachOfTenancyConditionsGroundLabel: `Breach of tenancy conditions (ground 12)`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  charitableLandlordsGround11Label: `Charitable landlords (ground 11)`,
  continueLabel: `Continue`,
  deathOfTheTenantGroundLabel: `Death of the tenant (ground 7)`,
  deteriorationInTheConditionOfLabel: `Deterioration in the condition of the property (ground 13)`,
  deteriorationInTheConditionOfLabel2: `Deterioration in the condition of the property (ground 3)`,
  deteriorationOfFurnitureGround15Label: `Deterioration of furniture (ground 15)`,
  deteriorationOfFurnitureGround4Label: `Deterioration of furniture (ground 4)`,
  discretionaryGroundsIfAlternativeAccomodationLabel: `Discretionary grounds (if alternative accomodation available)`,
  discretionaryGroundsLabel: `Discretionary grounds`,
  domesticViolenceGround14aLabel: `Domestic violence (ground 14A)`,
  domesticViolenceGround2aLabel: `Domestic violence (ground 2A)`,
  employeeOfTheLandlordGroundLabel: `Employee of the landlord (ground 16)`,
  holidayLetGround3Label: `Holiday let (ground 3)`,
  housingAssociationSpecialCircumstancesAccommodationLabel: `Housing association special circumstances accommodation (ground 14)`,
  key123456789101Label: `#1234-5678-9101`,
  landlordsWorksGround10Label: `Landlord’s works (ground 10)`,
  makeAClaimCaption: `Make a claim`,
  mandatoryGroundsIfAlternativeAccomodationLabel: `Mandatory grounds (if alternative accomodation available)`,
  mandatoryGroundsLabel: `Mandatory grounds`,
  nuisanceAnnoyanceIllegalOrImmoralLabel: `Nuisance, annoyance, illegal or immoral use of the property (ground 14)`,
  nuisanceAnnoyanceIllegalOrImmoralLabel2: `Nuisance, annoyance, illegal or immoral use of the property (ground 2)`,
  offenceDuringARiotGroundLabel: `Offence during a riot (ground 14ZA)`,
  offenceDuringARiotGroundLabel2: `Offence during a riot (ground 2ZA)`,
  overcrowdingGround9Label: `Overcrowding (ground 9)`,
  ownerOccupierGround1Label: `Owner occupier (ground 1)`,
  premiumPaidInConnectionWithLabel: `Premium paid in connection with mutual exchange (ground 6)`,
  previousLabel: `Previous`,
  propertyRequiredForMinisterOfLabel: `Property required for minister of religion (ground 5)`,
  propertyRequiredForRedevelopmentGroundLabel: `Property required for redevelopment (ground 6)`,
  propertySoldForRedevelopmentGroundLabel: `Property sold for redevelopment (ground 10A)`,
  refusalToMoveBackToLabel: `Refusal to move back to main home after works completed (ground 8)`,
  rentArrearsOrBreachOfLabel: `Rent arrears or breach of the tenancy (ground 1)`,
  repossessionByTheLandlordsMortgageLabel: `Repossession by the landlord's mortgage lender (ground 2)`,
  selectAllThatApplyHintText: `Select all that apply`,
  specialNeedsAccommodationGround15Label: `Special needs accommodation (ground 15)`,
  studentLetGround4Label: `Student let (ground 4)`,
  suitableAlternativeAccommodationGround9Label: `Suitable alternative accommodation (ground 9)`,
  tenancyObtainedByFalseStatementLabel: `Tenancy obtained by false statement (ground 17)`,
  tenancyObtainedByFalseStatementLabel2: `Tenancy obtained by false statement (ground 5)`,
  tenantDoesNotHaveALabel: `Tenant does not have a right to rent (ground 7B)`,
  tiedAccommodationNeededForAnotherLabel: `Tied accommodation needed for another employee (ground 12)`,
  underOccupyingAfterSuccessionGroundLabel: `Under occupying after succession (ground 15A)`,
  unreasonableConductInTiedAccommodationLabel: `Unreasonable conduct in tied accommodation (ground 7)`,
  youMayHaveAlreadyGivenLabel: `You may have already given the defendants notice of your intention to begin possession proceedings. If you have, you should have written the grounds you’re making your claim under. You should select these grounds here and any extra grounds you’d like to add to your claim, if you need to.

More information about possession grounds (opens in new tab).`
};
