ccd:
  enabled: true
  ccd:
    adminWeb:
      enabled: false
    definitionImporter:
      enabled: false
    userProfileImporter:
      enabled: false
    s2s:
      enabled: false
global:
  ccdApiGatewayIngress: http://${SERVICE_NAME}-ccd-api-gw
  ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store
  ccdUserProfileUrl: http://${SERVICE_NAME}-ccd-user-profile-api
  dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
  s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
