wiremock:
  enabled: true
  image: "wiremock/wiremock"
  applicationPort: 8080
  imagePullPolicy: Always
  releaseNameOverride : ${SERVICE_NAME}-wiremock
  ingressHost: wiremock-${SERVICE_NAME}.preview.platform.hmcts.net
  volumes:
    - name: wiremock-mocks
      configMap:
        name: ${SERVICE_NAME}-wiremock-wm
  volumeMounts:
    - name: wiremock-mocks
      mountPath: /home/wiremock/mappings
      subPath: mappings
  initialMappings:
    health-liveness.json: |
      {
        "request": {
          "method": "GET",
          "url": "/health/liveness"
        },
        "response": {
          "status": 200
        }
      }
    health.json: |
      {
        "request": {
          "method": "GET",
          "url": "/health"
        },
        "response": {
            "status": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "jsonBody": {
                "status": "OK",
                "components": {}
            }
        }
      }
    readiness.json: |
      {
        "request": {
          "method": "GET",
          "url": "/health/readiness"
        },
        "response": {
          "status": 200
        }
      }
    fee-register-proxy.json: |
      {
        "priority": 10,
        "request": {
          "method": "GET",
          "urlPath": "/fees-register/fees/lookup"
        },
        "response": {
          "proxyBaseUrl": "http://fees-register-api-aat.service.core-compute-aat.internal"
        }
      }
    fee-register-genapp-suspend.json: |
      {
        "priority": 1,
        "request": {
          "method": "GET",
          "urlPath": "/fees-register/fees/lookup",
          "queryParameters": {
            "service": {
              "equalTo": "general"
            },
            "jurisdiction1": {
              "equalTo": "civil"
            },
            "jurisdiction2": {
              "equalTo": "civil"
            },
            "channel": {
              "equalTo": "default"
            },
            "event": {
              "equalTo": "general application"
            },
            "keyword": {
              "equalTo": "ApplicationToVaryJudgmentOrSuspendEnforcement"
            }
          }
        },
        "response": {
          "status": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "jsonBody": {
            "code": "FEE0458",
            "description": "Stub for application to vary a judgment or suspend enforcement",
            "version": 1,
            "fee_amount": 16.0
          }
        }
      }
    rd-professional-proxy.json: |
      {
        "request": {
          "method": "GET",
          "urlPathPattern": "/refdata/internal/v1/organisations/orgDetails/.*"
        },
        "response": {
          "proxyBaseUrl": "http://rd-professional-api-aat.service.core-compute-aat.internal"
        }
      }

java:
  environment:
    FEES_REGISTER_API_URL: "https://wiremock-${SERVICE_NAME}.preview.platform.hmcts.net"
    RD_PROFESSIONAL_API_URL: "https://wiremock-${SERVICE_NAME}.preview.platform.hmcts.net"
