ccd:
  enabled: true
  ccd:
    adminWeb:
      enabled: false
    definitionImporter:
      enabled: false
    userProfileImporter:
      enabled: false
    s2s:
      enabled: false
    am-role-assignment-service:
      java:
        ingressHost: am-role-assignment-service-${SERVICE_FQDN}
        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 1
        environment:
          ROLE_ASSIGNMENT_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
          ROLE_ASSIGNMENT_DB_HOST: '{{ tpl .Values.global.postgresHostname $}}'
          ROLE_ASSIGNMENT_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
        keyVaults:
          am:
            secrets:
              - name: role-assignment-service-LD-SDK-KEY
                alias: LD_SDK_KEY
  ccd-user-profile-api:
    java:
      disableKeyVaults: true
      imagePullPolicy: Always
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
      environment:
        USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin,sscs
      keyVaults: [ ]

  ccd-definition-store-api:
    java:
      disableKeyVaults: true
      devmemoryRequests: '1024Mi'
      devmemoryLimits: '2048Mi'
      devcpuRequests: '500m'
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
      imagePullPolicy: Always
      environment:
        DEFINITION_STORE_DB_HOST: '{{ tpl .Values.global.postgresHostname $}}'
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        DEFINITION_STORE_TX_TIMEOUT_DEFAULT: 360
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
        WELSH_TRANSLATION_ENABLED: false
        DEFINITION_STORE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
        DEFINITION_STORE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
      ingressHost: ccd-definition-store-${SERVICE_FQDN}

  ccd-data-store-api:
    java:
      disableKeyVaults: true
      imagePullPolicy: Always
      devmemoryRequests: '1524Mi'
      devmemoryLimits: '2048Mi'
      devcpuRequests: '500m'
      environment:
        DATA_STORE_DB_HOST: '{{ tpl .Values.global.postgresHostname $}}'
        DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
        DATA_STORE_IDAM_KEY: ${CCD_DATA_STORE_S2S_SECRET}
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        DATA_STORE_CROSS_JURISDICTIONAL_ROLES: caseworker-caa,caseworker-approver
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS:  http://${SERVICE_NAME}-es-master:9200
        HTTP_CLIENT_READ_TIMEOUT: '120000'
        HTTP_CLIENT_MAX_TOTAL: '300'
        HTTP_CLIENT_MAX_CLIENT_PER_ROUTE: '30'
        DATA_STORE_DB_MAX_POOL_SIZE: 80
        DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
        CCD_DOCUMENT_URL_PATTERN: ^https?://(((?:dm-store-aat\.service\.core-compute-aat\.internal(?::\d+)?)\/documents\/[A-Za-z0-9-]+(?:\/binary)?))
        CASE_DOCUMENT_AM_URL: ${CASE_DOCUMENT_AM_URL}
        UPLOAD_TIMESTAMP_FEATURED_CASE_TYPES: CARE_SUPERVISION_EPO
        DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 1

  ccd-api-gateway-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/api-gateway-web:prod-66a4048-20250203150702
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_SECRET}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
        ALLOW_CONFIG_MUTATIONS: true
      ingressIP: ${INGRESS_IP}
      ingressHost: gateway-${SERVICE_FQDN}
      disableKeyVaults: true
global:
  ccdApiGatewayIngress: http://${SERVICE_NAME}-ccd-api-gw
  ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store
  ccdUserProfileUrl: http://${SERVICE_NAME}-ccd-user-profile-api
  dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
  s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
