ccd:
  elasticsearch:
    persistence:
      enabled: true
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenDeleted: Delete
      whenScaled: Delete
    volumeClaimTemplate:
      resources:
        requests:
          storage: 500Mi
      storageClassName: managed-lrs
