// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "ExUI - Check your answers (including content) - Rent arrears " (2001:23938) and other states

export const checkYourAnswers = {
  mainHeader: `Check your answers`,
  areYouAlsoMakingALabel: `Are you also making a claim for an order imposing a Prohibited conduct standard contract?`,
  areYouLicensedUnderPartLabel: `Are you licensed under Part 1 of the Housing (Wales) Act 2014?`,
  areYouPlanningToSubmitLabel: `Are you planning to submit a general application at the same time as your claim?`,
  areYouRegisteredUnderPartLabel: `Are you registered under Part 1 of the Housing (Wales) Act 2014?`,
  billyLabel: `Billy`,
  breachOfContractLabel: `Breach of contract`,
  byFirstClassPostOrLabel: `By first class post or other service which provides for delivery on the next business day`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  changeLink: `Change`,
  communityLandlordLabel: `Community landlord`,
  cymraegToggle: `Cymraeg`,
  dateTheDocumentWasPostedLabel: `Date the document was posted`,
  defendantsFirstNameLabel: `Defendant’s first name`,
  defendantsLastNameLabel: `Defendant’s last name`,
  detailsAboutBreachOfContractLabel: `Details about breach of contract`,
  detailsOfAsbLabel: `Details of ASB`,
  detailsOfIllegalPurposesLabel: `Details of illegal purposes`,
  detailsOfTheOtherProhibitedLabel: `Details of the other prohibited conduct`,
  discretionaryHousingPaymentLabel: `Discretionary Housing Payment`,
  doRentArrearsFormPartLabel: `Do rent arrears form part of the breach of contract?`,
  doYouKnowTheDefendantsLabel: `Do you know the defendant’s name?`,
  doYouKnowTheDefendantsLabel2: `Do you know the defendant’s correspondence address?`,
  doYouWantDocumentsToLabel: `Do you want documents to be sent to the address registered with My HMCTS?`,
  doYouWantTheCourtLabel: `Do you want the court to make a judgment for the outstanding arrears?`,
  doYouWantToAskLabel: `Do you want to ask for your costs back?`,
  doYouWantToProvideLabel: `Do you want to provide a contact phone number? (Optional)`,
  doYouWantToUploadLabel: `Do you want to upload a copy of the tenancy or licence agreement? (Optional)`,
  doYouWantToUploadLabel2: `Do you want to upload a copy of the notice you served or the certificate of service? (Optional)`,
  doYouWantToUploadLabel3: `Do you want to upload any additional documents?`,
  doYouWantToUseLabel: `Do you want to use this email address for notifications?`,
  forThePeriodShownOnLabel: `For the period shown on the rent statement, have any rent payments been paid by someone other than the defendants?`,
  formRhw23Label: `Form RHW23`,
  giveDetailsOfTheActualLabel: `Give details of the actual or threatened antisocial behaviour`,
  giveDetailsOfTheActualLabel2: `Give details of the actual or threatened use of the premises for illegal purposes`,
  giveDetailsOfTheOtherLabel: `Give details of the other prohibited conduct`,
  giveDetailsOfYourLicensedLabel: `Give details of your licensed agent`,
  hasThereBeenOtherProhibitedLabel: `Has there been other prohibited conduct?`,
  haveThereBeenAnyOtherLabel: `Have there been any other breaches of contract?`,
  haveYouAppointedALicensedLabel: `Have you appointed a licensed agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014??`,
  haveYouAppointedALicensedLabel2: `Have you appointed a licensed agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014?`,
  haveYouAttemptedMediationWithLabel: `Have you attempted mediation with the defendants?`,
  haveYouFollowedThePreactionLabel: `Have you followed the pre-action protocol?`,
  haveYouServedNoticeToLabel: `Have you served notice to the defendants?`,
  haveYouTriedToReachLabel: `Have you  tried to reach a settlement with the defendants?`,
  homelessPreventionFundLabel: `Homeless Prevention Fund`,
  housingBenefitLabel: `Housing Benefit`,
  howDidYouServeTheLabel: `How did you serve the notice?`,
  howFrequentlyShouldRentBeLabel: `How frequently should rent be paid?`,
  howMuchAreTheTotalLabel: `How much are the total rent arrears as shown on the rent statement?`,
  howMuchIsTheRentLabel: `How much is the rent?`,
  iBelieveThatTheFactsLabel: `I believe that the facts stated in this claim form are true.`,
  isTheAmountPerDayLabel: `Is the amount per day that unpaid rent should be charged at correct?`,
  isTheDefendantsCorrespondenceAddressLabel: `Is the defendant's correspondence address the same as the address of the property you're claiming possession of?`,
  isThereActualOrThreatenedLabel: `Is there actual or threatened antisocial behaviour?`,
  isThereActualOrThreatenedLabel2: `Is there actual or threatened use of the premises for illegal purposes?`,
  isThereAnUnderleseeOrLabel: `Is there an underlesee or mortgagee entitled to claim relief against forfeiture?`,
  isThereAnyInformationYoudLabel: `Is there any information you’d like to provide about Treetops Housing’s circumstances?`,
  isThereAnyInformationYoudLabel2: `Is there any information you’d like to provide about the defendants’ circumstances?`,
  isThereAnyOtherInformationLabel: `Is there any other information you’d like to provide about your reasons for possession?`,
  isThisTheCorrectClaimantLabel: `Is this the correct claimant name?`,
  key0422015Label: `04/2/2015`,
  key12345464576477Label: `12345464576477`,
  key125Label: `£125`,
  key1625Label: `1/6/25`,
  key3050Label: `£3050`,
  key32343434335435Label: `32343434335435`,
  key54PenrhynAvenueBangorLl57Label: `54 Penrhyn Avenue
Bangor
LL57 4AA`,
  noOption: `No`,
  notice54penrhynavenuepdfLabel: `Notice_54_Penrhyn_Avenue.pdf`,
  occupationContractHoldersLabel: `Occupation contract holders`,
  occupationcontract54penrhynavenuepdfLabel: `Occupation_contract_54_Penrhyn_Avenue.pdf`,
  paulSmith1234353554525118Label: `Paul Smith
12343535545
25/1/18`,
  previousLabel: `Previous`,
  provideDetailsOfYourLicensedLabel: `Provide details of your licensed agent`,
  rentstatement54penrhynavenuepdfLabel: `Rent_statement_54_Penrhyn_Avenue.pdf`,
  secureContractLabel: `Secure contract`,
  statementOfTruthLabel: `Statement of truth`,
  submitAndPayLabel: `Submit  and pay`,
  submitAndPayLabel2: `Submit and pay`,
  theDefendantLivesWithTheirLabel: `The defendant lives with their 3 children at the property. They are receiving Universal Credit and housing benefit and are in part-time employment. No deductions are being made from their benefits to pay off the arrears.`,
  universalCreditLabel: `Universal Credit`,
  uploadTheRentStatementLabel: `Upload the rent statement`,
  weeklyLabel: `Weekly`,
  wereYouLicensedUnderPartLabel: `Were you licensed under Part 1 of the Housing (Wales) Act 2014?`,
  wereYouRegisteredUnderPartLabel: `Were you registered under Part 1 of the Housing (Wales) Act 2014?`,
  whatAreYourGroundsForLabel: `What are your grounds for possession?`,
  whatDateDidTheOccupationLabel: `What date did the occupation contract or licence begin? (Optional)`,
  whatDateDidTheOccupationLabel2: `What date did the occupation contract or licence begin?`,
  whatIsTheAddressOfLabel: `What is the address of the property you’re claiming possession of?`,
  whatTypeOfNoticeDidLabel: `What type of notice did you serve?`,
  whatTypeOfOccupationContractLabel: `What type of occupation contract or licence is in place?`,
  whatsYourLicenceNumberLabel: `What’s your licence number?`,
  whatsYourRegistrationNumberLabel: `What’s your registration number?`,
  whereHaveThePaymentsComeLabel: `Where have the payments come from?`,
  whoAreYouMakingALabel: `Who are you making a possession claim against?`,
  whoIsTheClaimantInLabel: `Who is the claimant in this case?`,
  whyAreYouMakingALabel: `Why are you making a claim for possession under breach of contract?`,
  wrightLabel: `Wright`,
  yesOption: `Yes`
};
