// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "Welsh claimant details combined / not applicable" (2345:104645) and other states

export const claimantDetails = {
  mainHeader: `Claimant details`,
  agentsDateOfAppointmentLabel: `Agent’s date of appointment`,
  agentsFirstNameLabel: `Agent’s first name`,
  agentsLastNameLabel: `Agent’s last name`,
  agentsLicenceNumberLabel: `Agent’s licence number`,
  areYouLicencedUnderPartLabel: `Are you licenced under Part 1 of the Housing (Wales) Act 2014?`,
  areYouLicensedUnderPartLabel: `Are you licensed under Part 1 of the Housing (Wales) Act 2014?`,
  areYouRegisteredUnderPartLabel: `Are you registered under Part 1 of the Housing (Wales) Act 2014?`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  cymraegToggle: `Cymraeg`,
  dayLabel: `Day`,
  forExample1642021HintText: `For example, 16 4 2021`,
  giveDetailsOfYourLicencedLabel: `Give details of your licenced agent`,
  giveDetailsOfYourLicensedLabel: `Give details of your licensed agent`,
  haveYouAppointedALicencedLabel: `Have you appointed a licenced agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014?`,
  haveYouAppointedALicencedLabel2: `Have you appointed a licenced agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014??`,
  haveYouAppointedALicencedLabel3: `Have you appointed a licenced agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014`,
  haveYouAppointedALicensedLabel: `Have you appointed a licensed agent to be responsible for all the property management work in relation to the dwelling as permitted under Part 1 of the Housing (Wales) Act 2014?`,
  iWantToSaveThisLabel: `I want to save this application and return to it later`,
  makeAClaimCaption: `Make a claim`,
  monthLabel: `Month`,
  noOption: `No`,
  notApplicableLabel: `Not applicable`,
  previousLabel: `Previous`,
  provideDetailsOfYourLicencedLabel: `Provide details of your licenced agent`,
  provideDetailsOfYourLicensedLabel: `Provide details of your licensed agent`,
  wereYouLicencedUnderPartLabel: `Were you licenced under Part 1 of the Housing (Wales) Act 2014?`,
  wereYouLicensedUnderPartLabel: `Were you licensed under Part 1 of the Housing (Wales) Act 2014?`,
  wereYouRegisteredUnderPartLabel: `Were you registered under Part 1 of the Housing (Wales) Act 2014?`,
  whatsYourLicenceNumberLabel: `What’s your licence number?`,
  whatsYourRegistrationNumberLabel: `What’s your registration number?`,
  yearLabel: `Year`,
  yesOption: `Yes`
};
