// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "✅ GOV.UK Pay Common Component - Payment Details " (2001:27181) and other states

export const enterCardDetails = {
  mainHeader: `Enter card details`,
  acceptedCreditAndDebitCardHintText: `Accepted credit and debit card types`,
  admintreetopshousinggovukLabel: `admin@treetopshousing.gov.uk`,
  anEmailWillBeSentLabel: `An email will be sent to:
admin@treetopshousing.gov.uk`,
  billingAddressLabel: `Billing address`,
  buildingNumberOrNameAndLabel: `Building number or name and street`,
  cancelPaymentLabel: `Cancel payment`,
  cardNumberLabel: `Card number`,
  cardSecurityCodeLabel: `Card security code`,
  claimFeeLabel: `Claim fee`,
  contactDetailsLabel: `Contact details`,
  continueLabel: `Continue`,
  countryOrTerritoryLabel: `Country or territory`,
  emailLabel: `Email`,
  expiryDateLabel: `Expiry date`,
  forExample1025HintText: `For example, 10/25`,
  govukLabel: `GOV.UK`,
  key01Label: `01`,
  key1234567890123456Label: `1234 5678 9012 3456`,
  key123Label: `123`,
  key1HighStreetLabel: `1 High Street`,
  key28Label: `28`,
  key404Label: `£404`,
  lu11cdLabel: `LU1 1CD`,
  lutonLabel: `Luton`,
  monthLabel: `Month`,
  nameOnCardLabel: `Name on card`,
  paymentSummaryLabel: `Payment summary`,
  possessionClaimsLabel: `Possession claims`,
  postcodeLabel: `Postcode`,
  signOutLabel: `Sign out`,
  theLast3DigitsOnHintText: `The last 3 digits on the back of the card`,
  thisIsTheAddressAssociatedHintText: `This is the address associated with the card`,
  totalAmountLabel: `Total amount:`,
  townOrCityLabel: `Town or city`,
  treetopsHousingLabel: `Treetops Housing`,
  unitedKingdomLabel: `United Kingdom`,
  unnamedLabel: `/`,
  wellSendYourPaymentConfirmationHintText: `We’ll send your payment confirmation here`,
  yearLabel: `Year`
};
