// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "ExUI - Dashboard" (2001:25949) and other states

export const key54PenrhynAvenueBangorLl57 = {
  mainHeader: `54 Penrhyn Avenue, Bangor, LL57 4AA 
Case number: 1234-5678-9101-1213`,
  amountLabel: `Amount`,
  amountToPay40400Label: `Amount to pay
£404.00`,
  applicationLabel: `Application`,
  caseDetailsLabel: `Case details`,
  caseDocumentsLabel: `Case Documents`,
  caseFileViewLabel: `Case File View`,
  continueLabel: `Continue`,
  cymraegToggle: `Cymraeg`,
  enterAReferenceForYourLabel: `Enter a reference for your PBA account statements`,
  familymanIdCaseNumber1234567891011213Label: `FamilyMan ID:
Case number: 1234-5678-9101-1213`,
  goLabel: `Go`,
  hearingsLabel: `Hearings`,
  key202417163031067Label: `2024-17163031067`,
  key404Label: `£404`,
  linkedCasesLink: `Linked Cases`,
  nextStepLabel: `Next step`,
  notPaidLabel: `Not paid`,
  notesLabel: `Notes`,
  partiesLabel: `Parties`,
  partyLabel: `Party`,
  payFeeByCreditOrLabel: `Pay fee by credit or debit card`,
  payFeeUsingPaymentByLabel: `Pay fee using Payment by Account (PBA)`,
  payNowLabel: `Pay now`,
  paymentHistoryLabel: `Payment History`,
  pba0063742Label: `PBA0063742`,
  pba0073562Label: `PBA0073562`,
  pba0081571Label: `PBA0081571`,
  queriesTab: `Queries`,
  referenceDetailsLabel: `<Reference details>`,
  requestReferenceLabel: `Request reference`,
  reviewLabel: `Review`,
  rolesAndAccessLabel: `Roles and Access`,
  selectAnOptionLabel: `--Select an option--`,
  selectOptionLabel: `Select option`,
  selectPbaLabel: `Select PBA`,
  serviceRequestLabel: `Service Request`,
  statusLabel: `Status`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  thisShouldBeYourOwnHintText: `This should be your own unique reference to identify the case.  It will appear on your statement`,
  treetopsHousingLabel: `Treetops Housing`
};
