// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "Notice served /  none selected" (2001:155670) and other states

export const noticeDetails = {
  mainHeader: `Notice details`,
  addDocumentLabel: `Add document`,
  addNewLabel: `Add new`,
  billyWrightLabel: `Billy Wright`,
  byDeliveringItToOrLabel: `By delivering it to or leaving it at a permitted place`,
  byEmailLabel: `By email`,
  byFirstClassPostOrLabel: `By first class post or other service which provides for delivery on the next business day`,
  byOtherElectronicMethodLabel: `By other electronic method`,
  byPersonallyHandingItToLabel: `By personally handing it to or leaving it with someone`,
  cancelLabel: `Cancel`,
  cancelUploadLabel: `Cancel upload`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  chooseFileLabel: `Choose file`,
  continueLabel: `Continue`,
  cymraegToggle: `Cymraeg`,
  dateAndTimeTheDocumentLabel: `Date and time the document was handed over`,
  dateTheDocumentWasPostedLabel: `Date the document was posted`,
  dayLabel: `Day`,
  doYouWantToUploadLabel: `Do you want to upload a copy of the notice you served or the certificate of service? (Optional)`,
  documentLabel: `Document`,
  forExample1642021HintText: `For example, 16 4 2021`,
  forExample1642021HintText2: `For example, 16 4 2021, 11 15`,
  hourLabel: `Hour`,
  howDidYouServeTheLabel: `How did you serve the notice?`,
  key14Label: `14`,
  key19Label: `19`,
  key2025Label: `2025`,
  key28Label: `28`,
  key4Label: `4`,
  makeAClaimCaption: `Make a claim`,
  minuteLabel: `Minute`,
  monthLabel: `Month`,
  nameOfPersonTheDocumentLabel: `Name of person the document was left with`,
  noFileSelectedLabel: `No file selected`,
  notice15gardendrivepdfLabel: `Notice_15_Garden-Drive.pdf`,
  otherLabel: `Other`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  yearLabel: `Year`,
  youCanEitherUploadTheseHintText: `You can either upload these now or closer to the hearing date. Any documents you upload now will be included in the pack of documents a judge will receive before the hearing (the bundle)`
};
