// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "OC details" (2001:19351) and other states

export const occupationContractOrLicenceDetails = {
  mainHeader: `Occupation contract or licence details`,
  addDocumentLabel: `Add document`,
  addNewLabel: `Add new`,
  cancelLabel: `Cancel`,
  cancelUploadLabel: `Cancel upload`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  chooseFileLabel: `Choose file`,
  continueLabel: `Continue`,
  cymraegToggle: `Cymraeg`,
  dayLabel: `Day`,
  doYouWantToUploadLabel: `Do you want to upload a copy of the occupation contract or licence? (Optional)`,
  documentLabel: `Document`,
  documentpdfLabel: `Document.pdf`,
  forExample1642021HintText: `For example, 16 4 2021`,
  giveDetailsAboutWhatTypeLabel: `Give details about what type of occupation contract or licence is in place`,
  iWantToSaveThisLabel: `I want to save this application and return to it later`,
  key18Label: `18`,
  key2022Label: `2022`,
  key6Label: `6`,
  makeAClaimCaption: `Make a claim`,
  monthLabel: `Month`,
  occupationContractOrLicenceStartLabel: `Occupation contract or licence start date`,
  occupationContractOrLicenceTypeLabel: `Occupation contract or licence type`,
  otherLabel: `Other`,
  pleaseEnterDateLabel: `Please enter date`,
  previousLabel: `Previous`,
  removeLabel: `Remove`,
  secureContractLabel: `Secure contract`,
  standardContractLabel: `Standard contract`,
  uploadADocumentToTheLabel: `Upload a document to the system`,
  uploadOccupationContractOrLicenceLabel: `Upload occupation contract or licence`,
  whatDateDidTheOccupationLabel: `What date did the occupation contract or licence begin? (Optional)`,
  whatDateDidTheSecureLabel: `What date did the secure occupation contract begin?`,
  whatTypeOfOccupationContractLabel: `What type of occupation contract or licence is in place?`,
  yearLabel: `Year`,
  youCanEitherUploadThisHintText: `You can either upload this now or closer to the hearing date. Any documents you upload now will be included in the pack of documents a judge will receive before the hearing (the bundle)`,
  youCanEitherUploadThisHintText2: `You can either upload this now or closer to the hearing date. Any documents you upload now will be included in the pack of documents a judge will receive before the hearing (the bundle).`
};
