// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "Claim details / not paid" (2001:27442) and other states

export const possessionDetails = {
  mainHeader: `Possession details`,
  addressLabel: `Address`,
  bangorLabel: `Bangor`,
  billyLabel: `Billy`,
  breachOfContractLabel: `Breach of contract`,
  buildingAndStreetLabel: `Building and Street`,
  caseDetailsLabel: `Case details`,
  caseFileViewLabel: `Case File View`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  caseNumber123456789101Label: `Case number: 1234-5678-9101`,
  claimantDetailsLabel: `Claimant details`,
  claimantNameLabel: `Claimant name`,
  claimantsDetailsLabel: `Claimant's details`,
  countryLabel: `Country`,
  cymraegToggle: `Cymraeg`,
  dateClaimSubmittedLabel: `Date claim Submitted`,
  defendantDetailsLabel: `Defendant details`,
  firstNameLabel: `First name`,
  goLabel: `Go`,
  gourndsForPossessionLabel: `Gournds for possession`,
  hearingsLabel: `Hearings`,
  key1HighStreetLabel: `1 High Street`,
  key54PenrhynAvenueBangorLl57Label: `54 Penrhyn Avenue, Bangor, LL57 4AA`,
  key54PenrhynAvenueLabel: `54 Penrhyn Avenue`,
  key6May202510AmLabel: `6 May 2025, 10 AM`,
  lastNameLabel: `Last name`,
  linkedCasesLink: `Linked Cases`,
  ll574aaLabel: `LL57 4AA`,
  lu11bcLabel: `LU1 1BC`,
  lutonLabel: `Luton`,
  nextStepLabel: `Next step`,
  notesLabel: `Notes`,
  organisationAddressLabel: `Organisation Address`,
  partiesLabel: `Parties`,
  paymentHistoryLabel: `Payment History`,
  pba1356448Label: `PBA1356448`,
  pbaNumberLabel: `PBA Number`,
  postcodezipcodeLabel: `Postcode/Zipcode`,
  propertyDetailsLabel: `Property details`,
  queriesTab: `Queries`,
  reviewTheClaimBeforeYouLabel: `Review the claim before you sign, submit and pay.`,
  rolesAndAccessLabel: `Roles and Access`,
  selectActionLabel: `Select action`,
  serviceRequestLabel: `Service Request`,
  summaryLabel: `Summary`,
  supportTab: `Support`,
  tasksLabel: `Tasks`,
  townOrCityLabel: `Town or City`,
  treetopsHousingLabel: `Treetops Housing`,
  unitedKingdomLabel: `United Kingdom`,
  whatHappensNextLabel: `What happens next`,
  wrightLabel: `Wright`
};
