// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "Underlessee" (2001:100758) and other states

export const underlesseeOrMortgageesDetails = {
  mainHeader: `Underlessee or mortgagee's details`,
  addressLine2OptionalLabel: `Address line 2 (Optional)`,
  addressLine3OptionalLabel: `Address line 3 (Optional)`,
  bradDolanLabel: `Brad Dolan`,
  buildingAndStreetLabel: `Building and Street`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  continueLabel: `Continue`,
  countryOptionalLabel: `Country (Optional)`,
  countyOptionalLabel: `County (Optional)`,
  cymraegToggle: `Cymraeg`,
  doYouKnowTheirCorrespondenceLabel: `Do you know their correspondence address?`,
  doYouKnowTheirNameLabel: `Do you know their name?`,
  enterAUkPostcodeLabel: `Enter a UK postcode`,
  enterAddressDetailsLabel: `Enter address details`,
  enterTheirFirstNameAndHintText: `Enter their first name and last name.`,
  findAddressLabel: `Find address`,
  key14LongStreetLabel: `14 Long Street`,
  key14LongStreetLutonLabel: `14 Long Street, Luton`,
  lu56tbLabel: `LU5 6TB`,
  lutonLabel: `Luton`,
  makeAClaimCaption: `Make a claim`,
  noOption: `No`,
  postcodeLabel: `Postcode`,
  previousLabel: `Previous`,
  selectAnAddressLabel: `Select an address`,
  townOrCityLabel: `Town or City`,
  underlesseeOrMortgageeCorrespondenceAddressLabel: `Underlessee or mortgagee correspondence address`,
  underlesseeOrMortgageeNameLabel: `Underlessee or mortgagee name`,
  whatIsTheirNameLabel: `What is their name?`,
  yesOption: `Yes`
};
