// Auto-generated from Figma file: ez65eYH9Xwj2i5BLKt65nu, based on page: "Welsh GfP / none selected" (2001:19824) and other states

export const whatAreYourGroundsFor = {
  mainHeader: `What are your grounds for possession?`,
  antisocialBehaviourBreachOfContractLabel: `Antisocial behaviour (breach of contract) (section 157)`,
  antisocialBehaviourBreachOfContractLabel2: `Antisocial behaviour (breach of contract)`,
  buildingWorksGroundALabel: `Building works (ground A)`,
  cancelLabel: `Cancel`,
  caseNumber1234567891011213Label: `Case number: 1234-5678-9101-1213`,
  charitiesGroundCLabel: `Charities (ground C)`,
  continueLabel: `Continue`,
  contractholderUnderAFixedTermLabel: `Contract-holder under a fixed term standard contract seriously in arrears with rent (section 187)`,
  contractholderUnderAFixedTermLabel2: `Contract-holder under a fixed term standard contract seriously in arrears with rent  (section 187)`,
  contractholderUnderAFixedTermLabel3: `Contract-holder under a fixed term standard contract seriously in arrears with rent`,
  contractholderUnderAPeriodicStandardLabel: `Contract-holder under a periodic standard contract seriously in arrears with rent (section 181)`,
  contractholderUnderAPeriodicStandardLabel2: `Contract-holder under a periodic standard contract seriously in arrears with rent`,
  cymraegToggle: `Cymraeg`,
  discretionaryGroundsLabel: `Discretionary grounds`,
  dwellingSuitableForDisabledPeopleLabel: `Dwelling suitable for disabled people (ground D)`,
  estateManagementGroundsLabel: `Estate management grounds`,
  estateManagementGroundsSection160Label: `Estate management grounds (section 160)`,
  failureToGiveUpPossessionLabel: `Failure to give up possession on date specified in contract-holder’s notice (section 170)`,
  failureToGiveUpPossessionLabel2: `Failure to give up possession on date specified in contract-holder’s break clause notice (section 191)`,
  failureToGiveUpPossessionLabel22: `Failure to give up possession on date specified in contract-holder’s break clause notice`,
  failureToGiveUpPossessionLabel3: `Failure to give up possession on date specified in contract-holder’s notice`,
  groupsOfDwellingsForPeopleLabel: `Groups of dwellings for people with special needs (ground F)`,
  housingAssociationsAndHousingTrustsLabel: `Housing associations and housing trusts: people difficult to house (ground E)`,
  iWantToSaveThisLabel: `I want to save this application and return to it later`,
  jointContractholdersGroundHLabel: `Joint contract-holders (ground H)`,
  landlordsNoticeGivenInRelationLabel: `Landlord’s notice given in relation to periodic standard contract (section 178)`,
  landlordsNoticeGivenInRelationLabel2: `Landlord’s notice given in relation to periodic standard contract`,
  landlordsNoticeInConnectionWithLabel: `Landlord’s notice in connection with end of fixed term given (section 186)`,
  landlordsNoticeInConnectionWithLabel2: `Landlord’s notice in connection with end of fixed term given`,
  makeAClaimCaption: `Make a claim`,
  mandatoryGroundsLabel: `Mandatory grounds`,
  noticeGivenInRelationToLabel: `Notice given in relation to end of converted fixed term standard contract (paragraph 25B(2) of Schedule 12)`,
  noticeGivenInRelationToLabel2: `Notice given in relation to end of converted fixed term standard contract`,
  noticeGivenUnderALandlordsLabel: `Notice given under a landlord’s break clause (section 199)`,
  noticeGivenUnderALandlordsLabel2: `Notice given under a landlord’s break clause`,
  otherBreachOfContractLabel: `Other breach of contract`,
  otherBreachOfContractSectionLabel: `Other breach of contract (section 157)`,
  otherEstateManagementGroundsLabel: `Other estate management grounds`,
  otherEstateManagementReasonsGroundLabel: `Other estate management reasons (ground I)`,
  previousLabel: `Previous`,
  redevelopmentSchemesGroundBLabel: `Redevelopment schemes (ground B)`,
  rentArrearsBreachOfContractLabel: `Rent arrears (breach of contract) (section 157)`,
  rentArrearsBreachOfContractLabel2: `Rent arrears (breach of contract)`,
  reserveSuccessorsGroundGLabel: `Reserve successors (ground G)`,
  selectAllThatApplyHintText: `Select all that apply`,
  youMayHaveAlreadyGivenLabel: `You may have already given the defendants notice of your intention to begin possession proceedings. If you have, you should have written the grounds you’re making your claim under. You should select these grounds here and select any extra grounds you’d like to add to your claim, if you need to.

More information about possession grounds (opens in new tab).`
};
