package uk.gov.hmcts.reform.pcs.postcodecourt.service;

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

@Service
public class PartialPostcodesGenerator {

    /**
     * Generates a list of partial postcodes based on the provided full postcode. The partial
     * postcodes are generated by starting with the full postcode and repeatedly removing the
     * last character from the inbound code.
     * @param postcode The postcode to generate partial postcodes for
     * @return A list of partial postcodes, including the provided full postcode
     */
    public List<String> generateForPostcode(String postcode) {
        int maxTrim = 3;
        String partialPostcode = postcode.replaceAll("\\s", "").toUpperCase(Locale.ROOT);
        List<String> partialPostcodes = new ArrayList<>();
        partialPostcodes.add(partialPostcode);
        for (int i = 0; i < maxTrim && partialPostcode.length() > 2; i++) {
            partialPostcode = partialPostcode.substring(0, partialPostcode.length() - 1);
            partialPostcodes.add(partialPostcode);
        }
        return partialPostcodes;
    }

}
