package uk.gov.hmcts.reform.pcs.ccd.service.order;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import uk.gov.hmcts.ccd.sdk.testing.CcdEventTestSupport;
import uk.gov.hmcts.ccd.sdk.testing.CcdEventTestSupport.Actor;
import uk.gov.hmcts.ccd.sdk.testing.ExternalEvent;
import uk.gov.hmcts.reform.ccd.document.am.model.Document;
import uk.gov.hmcts.reform.docassembly.domain.FormPayload;
import uk.gov.hmcts.reform.docassembly.domain.OutputType;
import uk.gov.hmcts.reform.pcs.ccd.domain.PCSCase;
import uk.gov.hmcts.reform.pcs.ccd.domain.State;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.ConfirmOrderReviewRequest;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.ConfirmOrderReviewRequest.Issue;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.ConfirmOrderReviewRequest.IssuedOrder;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.MakeOrderRequest;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.MakeOrderRequest.OrderChange;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.OrderStart;
import uk.gov.hmcts.reform.pcs.ccd.domain.order.OrderStart.Order;
import uk.gov.hmcts.reform.pcs.ccd.service.order.OrderDocumentService.Generation;
import uk.gov.hmcts.reform.pcs.config.IssuedCases;
import uk.gov.hmcts.reform.pcs.config.OrderEventIT;
import uk.gov.hmcts.reform.pcs.document.model.order.OrderDocumentPayload;
import uk.gov.hmcts.reform.pcs.document.model.order.OrderDocumentPayload.OrderParty;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static uk.gov.hmcts.reform.pcs.ccd.domain.order.ConfirmOrderReviewRequest.Action.ISSUE;
import static uk.gov.hmcts.reform.pcs.ccd.domain.order.MakeOrderRequest.Action.SAVE_DRAFT;
import static uk.gov.hmcts.reform.pcs.ccd.domain.order.MakeOrderRequest.Action.SUBMIT_FOR_REVIEW;
import static uk.gov.hmcts.reform.pcs.ccd.domain.order.OrderSeal.COUNTY_COURT;
import static uk.gov.hmcts.reform.pcs.ccd.event.order.ConfirmOrderReview.CONFIRM_ORDER_REVIEW;
import static uk.gov.hmcts.reform.pcs.ccd.event.order.MakeOrder.MAKE_ORDER;

/**
 * The document of an order a caseworker issued: generated by the job the issuing event schedules, rendered
 * from the order's wording into the order template with the case, its parties and the judge who made it, and
 * added to the case in a system event on the caseworker's behalf.
 */
@DisplayName("Issued order document")
class OrderDocumentIT extends OrderEventIT {

    private static final String WORDING = "<p>IT IS ORDERED THAT:</p><ol><li><p>Possession.</p></li></ol>";
    private static final String DM_STORE_URL = "http://dm-store/documents/" + UUID.randomUUID();

    @Autowired
    private CcdEventTestSupport<PCSCase, State> events;
    @Autowired
    private IssuedCases cases;
    @Autowired
    private OrderDocumentService orderDocumentService;

    @Test
    @DisplayName("renders the issued order's wording with the case, its parties and the judge, and adds it to the case")
    void rendersAndAttachesTheIssuedOrder() {
        long caseReference = cases.issue();
        Actor judge = events.registerActor("Sarah", "Hughes", "caseworker-pcs");
        Actor caseworker = events.registerActor("Tom", "Baker", "caseworker-pcs");
        ExternalEvent<OrderStart, MakeOrderRequest> asJudge = events.external(caseReference, MAKE_ORDER).as(judge);
        asJudge.submitExpectingSuccess(new MakeOrderRequest(SAVE_DRAFT,
            new OrderChange(null, 0, "OUTRIGHT_POSSESSION", Map.of(), null), null));
        Order draft = asJudge.start().order();
        asJudge.submitExpectingSuccess(new MakeOrderRequest(SUBMIT_FOR_REVIEW, new OrderChange(
            draft.id(), draft.version(), draft.orderType(), draft.formData(), null), null));
        var asCaseworker = events.external(caseReference, CONFIRM_ORDER_REVIEW).as(caseworker)
            .withClientContext(Map.of("orderId", draft.id().toString()));
        Order submitted = asCaseworker.start().order();
        when(docAssemblyService.generateDocument(any(), anyString(), any(), anyString())).thenReturn(DM_STORE_URL);
        when(caseDocumentClientApi.getMetadataForDocument(any(), any(), any())).thenReturn(storedDocument());

        asCaseworker.submitExpectingSuccess(new ConfirmOrderReviewRequest(ISSUE, submitted.id(),
            submitted.version(), "staff-review", null,
            new Issue(new IssuedOrder("OUTRIGHT_POSSESSION", Map.of(), null, WORDING),
                List.of(), true, true, true, List.of(), COUNTY_COURT)));
        scheduler.triggerCheckForDueExecutions();
        awaitDocument(submitted.id());

        String caseNumber = String.valueOf(caseReference).replaceAll("(\\d{4})(\\d{4})(\\d{4})(\\d{4})", "$1-$2-$3-$4");
        OrderDocumentPayload rendered = rendered(caseNumber).getFirst();
        assertThat(rendered.getJudgeName()).isEqualTo("Sarah Hughes");
        assertThat(rendered.isCountyCourtSeal()).isTrue();
        assertThat(rendered.isHighCourtSeal()).isFalse();
        assertThat(rendered.getOrderHtml()).isEqualTo(WORDING);
        assertThat(rendered.getParties()).contains(new OrderParty(IssuedCases.DEFENDANT, "Defendant"));
        assertThat(jdbcTemplate.queryForMap("""
            SELECT d.type, d.file_name, d.category_id FROM orders o JOIN document d ON d.id = o.document_id
            WHERE o.id = ?""", submitted.id()))
            .containsEntry("type", "ORDER")
            .containsEntry("file_name", "Order for possession.pdf")
            .containsEntry("category_id", "ordersAndNoticeOfHearings");
        var history = events.history(caseReference).getLast();
        assertThat(history.eventId()).isEqualTo("orderDocumentGenerated");
        assertThat(history.userId()).isEqualTo(caseworker.uid());

        // A re-run, as a retried job is, renders nothing and adds no second document.
        orderDocumentService.generateAndAttach(new Generation(submitted.id(), caseworker.uid(), "Tom", "Baker"));
        assertThat(rendered(caseNumber)).hasSize(1);
    }

    /** The order documents rendered for a case; other cases' orders may be rendered by the same scheduler. */
    private List<OrderDocumentPayload> rendered(String caseNumber) {
        ArgumentCaptor<FormPayload> payload = ArgumentCaptor.forClass(FormPayload.class);
        verify(docAssemblyService, atLeastOnce()).generateDocument(payload.capture(),
            eq("CV-PCS-ORD-ENG-Order.docx"), eq(OutputType.PDF), eq("Order for possession"));
        return payload.getAllValues().stream()
            .map(OrderDocumentPayload.class::cast)
            .filter(rendered -> caseNumber.equals(rendered.getCaseNumber()))
            .toList();
    }

    /** Waits for the scheduled job to add the order's document. */
    private void awaitDocument(UUID orderId) {
        assertThat(await(() -> Boolean.TRUE.equals(jdbcTemplate.queryForObject(
            "SELECT document_id IS NOT NULL FROM orders WHERE id = ?", Boolean.class, orderId))))
            .as("the order's document was generated").isTrue();
    }

    /** The rendered order as CDAM describes it once Docmosis has stored it. */
    private static Document storedDocument() {
        Document document = Document.builder().originalDocumentName("Order for possession.pdf").build();
        document.links = new Document.Links();
        document.links.self = new Document.Link();
        document.links.self.href = DM_STORE_URL;
        document.links.binary = new Document.Link();
        document.links.binary.href = DM_STORE_URL + "/binary";
        return document;
    }
}
