CREATE TABLE public.case_review_date
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id UUID REFERENCES pcs_case (id),
  date DATE NOT NULL,
  reason VARCHAR(60) NOT NULL,
  description VARCHAR(500) NOT NULL
);

CREATE INDEX idx_case_review_date_case_id ON public.case_review_date(case_id);
