CREATE TABLE public.pre_issue_checklist
(
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                      TEXT NOT NULL,
  allow_manual_completion   BOOLEAN NOT NULL,
  scheduled_completion_time TIMESTAMP,
  completed                 BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at              TIMESTAMP,
  claim_id                  UUID REFERENCES public.claim (id),
  response_id               INTEGER REFERENCES public.defendant_response (id),
  counterclaim_id           UUID REFERENCES public.counter_claim (id),
  gen_app_id                UUID REFERENCES public.general_application (id)
);

CREATE INDEX idx_pre_issue_checklist_claim_id ON public.pre_issue_checklist(claim_id);
CREATE INDEX idx_pre_issue_checklist_response_id ON public.pre_issue_checklist(response_id);
CREATE INDEX idx_pre_issue_checklist_counterclaim_id ON public.pre_issue_checklist(counterclaim_id);
CREATE INDEX idx_pre_issue_checklist_gen_app_id ON public.pre_issue_checklist(gen_app_id);