CREATE TABLE translated_document (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id UUID REFERENCES claim (id),
  counterclaim_id UUID REFERENCES counter_claim (id),
  general_application_id UUID REFERENCES general_application (id),
  document_id UUID REFERENCES document(id) NOT NULL,
  language TEXT
);

CREATE INDEX idx_translated_document_claim ON translated_document(claim_id);
CREATE INDEX idx_translated_document_counterclaim ON translated_document(counterclaim_id);
CREATE INDEX idx_translated_document_genapp ON translated_document(general_application_id);

ALTER TABLE translated_document
  ADD CONSTRAINT chk_exactly_one_owner CHECK (num_nonnulls(claim_id, counterclaim_id, general_application_id) = 1);
