-- TODO: Better name, so we can also put email notifications here?
CREATE TABLE bulk_print_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id UUID NOT NULL REFERENCES pcs_case (id),
  pack_type TEXT NOT NULL,
  claim_id UUID REFERENCES claim (id),
  counterclaim_id UUID REFERENCES counter_claim (id),
  general_application_id UUID REFERENCES general_application (id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE,
  pack_send_status TEXT NOT NULL
);

--TODO: Add column, join table for specific parties?

CREATE INDEX idx_bulk_print_queue_case_id ON bulk_print_queue(case_id);
CREATE INDEX idx_bulk_print_queue_pack_send_status ON bulk_print_queue(pack_send_status);
-- CREATE INDEX idx_bulk_print_queue_claim ON bulk_print_queue(claim_id);
-- CREATE INDEX idx_bulk_print_queue_counterclaim ON bulk_print_queue(counterclaim_id);
-- CREATE INDEX idx_bulk_print_queue_genapp ON bulk_print_queue(general_application_id);

-- ALTER TABLE bulk_print_queue
--   ADD CONSTRAINT chk_exactly_one_owner CHECK (num_nonnulls(claim_id, counterclaim_id, general_application_id) = 1);
