-- The data model calls the hearing table case_hearing; in PCS it is the existing hearing table.
-- Key columns are nullable because hearings created before HMC integration have no keys.

ALTER TABLE public.hearing
  ADD COLUMN hearing_type_key VARCHAR(64) CONSTRAINT hearing_hearing_type_key_fk REFERENCES public.hearing_type (key),
  ADD COLUMN hearing_case_type_key VARCHAR(64) CONSTRAINT hearing_hearing_case_type_key_fk REFERENCES public.hearing_case_type (key),
  ADD COLUMN hearing_case_subtype_key VARCHAR(64) CONSTRAINT hearing_hearing_case_subtype_key_fk REFERENCES public.hearing_case_subtype (key),
  ADD COLUMN hearing_priority_key VARCHAR(64) CONSTRAINT hearing_hearing_priority_key_fk REFERENCES public.hearing_priority (key),
  ADD COLUMN hearing_channel_key VARCHAR(64) CONSTRAINT hearing_hearing_channel_key_fk REFERENCES public.hearing_channel (key),
  ADD COLUMN hearing_subchannel_key VARCHAR(64) CONSTRAINT hearing_hearing_subchannel_key_fk REFERENCES public.hearing_subchannel (key),
  ADD COLUMN listing_status_key VARCHAR(64) CONSTRAINT hearing_listing_status_key_fk REFERENCES public.listing_status (key),
  ADD COLUMN change_reason_key VARCHAR(64) CONSTRAINT hearing_change_reason_key_fk REFERENCES public.change_reasons (key),
  ADD COLUMN auto_list_change_reasons_key VARCHAR(64) CONSTRAINT hearing_auto_list_change_reasons_key_fk REFERENCES public.auto_list_change_reasons (key),
  ADD COLUMN case_management_cancellation_reason_key VARCHAR(64) CONSTRAINT hearing_case_management_cancellation_reason_key_fk REFERENCES public.case_management_cancellation_reason (key),
  ADD COLUMN actual_cancellation_reason_key VARCHAR(64) CONSTRAINT hearing_actual_cancellation_reason_key_fk REFERENCES public.actual_cancellation_reason (key),
  ADD COLUMN actual_part_heard_reason_key VARCHAR(64) CONSTRAINT hearing_actual_part_heard_reason_key_fk REFERENCES public.actual_part_heard_reason (key);

CREATE TABLE public.hearing_venue
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hearing_id INTEGER NOT NULL CONSTRAINT hearing_venue_hearing_fk REFERENCES public.hearing (id) ON DELETE CASCADE
);

CREATE INDEX idx_hearing_venue_hearing_id ON public.hearing_venue (hearing_id);

ALTER TABLE public.facilities
  ADD COLUMN hearing_venue_id INTEGER CONSTRAINT facilities_hearing_venue_fk REFERENCES public.hearing_venue (id);

CREATE TABLE public.hearing_judge
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hearing_id INTEGER NOT NULL CONSTRAINT hearing_judge_hearing_fk REFERENCES public.hearing (id) ON DELETE CASCADE,
  judge_type_key VARCHAR(64) CONSTRAINT hearing_judge_judge_type_fk REFERENCES public.judge_type (key),
  additional_roles_key VARCHAR(64) CONSTRAINT hearing_judge_additional_roles_fk REFERENCES public.additional_roles (key)
);

CREATE INDEX idx_hearing_judge_hearing_id ON public.hearing_judge (hearing_id);

CREATE TABLE public.hearing_party
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hearing_id INTEGER NOT NULL CONSTRAINT hearing_party_hearing_fk REFERENCES public.hearing (id) ON DELETE CASCADE,
  party_relationship_type_key VARCHAR(64) CONSTRAINT hearing_party_party_relationship_type_fk REFERENCES public.party_relationship_type (key),
  custody_status_key VARCHAR(64) CONSTRAINT hearing_party_custody_status_fk REFERENCES public.custody_status (key),
  sign_language_key VARCHAR(64) CONSTRAINT hearing_party_sign_language_fk REFERENCES public.sign_language (key),
  unavailable_type_key VARCHAR(64) CONSTRAINT hearing_party_unavailable_type_fk REFERENCES public.unavailable_type (key),
  interpreter_language_key VARCHAR(64) CONSTRAINT hearing_party_interpreter_language_fk REFERENCES public.interpreter_language (key)
);

CREATE INDEX idx_hearing_party_hearing_id ON public.hearing_party (hearing_id);
