CREATE TABLE public.hearing
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id UUID REFERENCES pcs_case (id),
  type VARCHAR(60) NOT NULL,
  other_hearing_type VARCHAR(100),
  notice_wording VARCHAR(60) NOT NULL,
  date DATE NOT NULL,
  duration_hours SMALLINT NOT NULL,
  duration_minutes SMALLINT NOT NULL,
  notes VARCHAR(500) NOT NULL,
  notice_issued YES_NO NOT NULL,
  is_without_notice YES_NO,
  additional_information VARCHAR(500) NOT NULL
);

CREATE INDEX idx_hearing_case_id ON public.hearing(case_id);

CREATE TABLE public.hearing_party
(
  hearing_id INTEGER REFERENCES hearing (id),
  party_id UUID REFERENCES party (id),
  primary key (hearing_id, party_id)
);

CREATE INDEX idx_hearing ON hearing_party(hearing_id);
