name: Diff CCD definition

on:
  pull_request:
    branches:
      - master

jobs:

  buildBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
      - uses: actions/checkout@v5
        with:
          path: build/branch
      - name: Build
        run: ./gradlew generateCCDConfig
        working-directory: build/branch
      - uses: actions/upload-artifact@v4
        with:
          name: branch
          path: build/branch/build/definitions/PCS

  buildMaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
      - uses: actions/checkout@v5
        with:
          ref: master
          path: build/master
      - name: Build
        run: ./gradlew generateCCDConfig
        working-directory: build/master
      - uses: actions/upload-artifact@v4
        with:
          name: master
          path: build/master/build/definitions/PCS

  report:
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: [buildBranch, buildMaster]
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: 16
      - uses: actions/download-artifact@v5
        with:
          name: branch
          path: build/branch
      - uses: actions/download-artifact@v5
        with:
          name: master
          path: build/master
      - name: Generate report
        id: ccd-diff
        run: |
          REPORT="$(npx -q @hmcts/ccd-diff build/master build/branch)"
          printf 'content<<EOF\n%s\nEOF\n' "$REPORT" >> "$GITHUB_OUTPUT"
      - name: Display
        run: |
          echo "${{ steps.ccd-diff.outputs.content }}"
      - name: Add report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          BODY_FILE="$(mktemp)"
          {
            printf '# CCD diff report\n\n'
            printf '%s\n' "${{ steps.ccd-diff.outputs.content }}"
          } > "$BODY_FILE"
          gh pr comment "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --body-file "$BODY_FILE"
