name: Cftlib Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  gradle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'
      - name: Run task
        run: ./gradlew -is cftlibTest

